# Generated by Django 6.0.2 on 2026-07-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=20)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('contectno', models.CharField(max_length=20)),
                ('seller_store_name', models.CharField(blank=True, max_length=20, null=True)),
                ('pic', models.FileField(default='images/seller_admin.jpg', upload_to='images/')),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('GSTNO', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('stock_qty', models.IntegerField()),
                ('picture', models.FileField(default='images/default.jpg', upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('discount', models.IntegerField(default=0)),
                ('badge_text', models.CharField(blank=True, default='', max_length=50)),
                ('weight_unit', models.CharField(default='100g', max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_sold', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0, help_text='Calories per serving')),
                ('protein', models.FloatField(default=0.0, help_text='Protein in grams')),
                ('carbs', models.FloatField(default=0.0, help_text='Carbohydrates in grams')),
                ('fat', models.FloatField(default=0.0, help_text='Fat in grams')),
                ('sugar', models.FloatField(default=0.0, help_text='Sugar in grams')),
                ('fiber', models.FloatField(default=0.0, help_text='Fiber in grams')),
                ('serving_size', models.CharField(default='100g', max_length=50)),
                ('ingredients', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('recommended_usage', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('diet_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Vegan', 'Vegan')], default='Veg', max_length=20)),
                ('goal_type', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Muscle Gain', 'Muscle Gain'), ('Maintenance', 'Maintenance')], default='Maintenance', max_length=30)),
                ('flavour', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_ai_recommended', models.BooleanField(default=False)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellerapp.category')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.user')),
            ],
        ),
    ]
