# Generated by Django 6.0.2 on 2026-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_tags',
            field=models.TextField(blank=True, help_text='Comma separated AI tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='health_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
