# Generated by Django 6.0.2 on 2026-02-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
