# Generated by Django 6.0.2 on 2026-03-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.FileField(default='media/set.jpg', upload_to='media/images/'),
        ),
    ]
