# Generated by Django 6.0.2 on 2026-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_alter_product_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pic',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='seller',
            name='pic',
            field=models.FileField(default='media/seller_admin.jpg', upload_to='media/images/'),
        ),
    ]
