# Generated by Django 6.0.2 on 2026-03-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_rename_pic_product_picture_seller_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(default='default.jpg', upload_to='media/images/'),
        ),
    ]
