# Generated by Django 6.0.2 on 2026-03-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0008_alter_product_picture_alter_seller_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pic',
            field=models.FileField(default='images/seller_admin.jpg', upload_to='images/'),
        ),
    ]
