# Generated by Django 6.0.2 on 2026-07-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=18)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('activity_level', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Light', 'Light'), ('Moderate', 'Moderate'), ('Active', 'Active'), ('Very Active', 'Very Active')], max_length=20)),
                ('goal', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Muscle Gain', 'Muscle Gain'), ('Maintenance', 'Maintenance')], max_length=30)),
                ('diet_type', models.CharField(choices=[('Veg', 'Veg'), ('Vegan', 'Vegan'), ('Non-Veg', 'Non-Veg')], max_length=20)),
                ('bmi', models.FloatField(default=0)),
                ('daily_calories', models.IntegerField(default=0)),
                ('protein_goal', models.FloatField(default=0)),
                ('carbs_goal', models.FloatField(default=0)),
                ('fat_goal', models.FloatField(default=0)),
                ('water_goal', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='customerapp.customer')),
            ],
        ),
    ]
