# Generated by Django 6.0.1 on 2026-03-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_alter_cartitem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
