# Generated by Django 6.0.2 on 2026-07-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('water', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='customerapp.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
