# Generated by Django 6.0.2 on 2026-07-10 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0011_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGamification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('streak', models.IntegerField(default=0)),
                ('ai_questions', models.IntegerField(default=0)),
                ('total_meals', models.IntegerField(default=0)),
                ('water_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer')),
            ],
        ),
    ]
