# Generated by Django 6.0.2 on 2026-07-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0012_usergamification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight', models.TextField()),
                ('health_score', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
