# Generated by Django 6.0.1 on 2026-07-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0013_dailyhealthinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Elite', 'Elite')], default='Free', max_length=20),
        ),
    ]
